trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '88669215-55be-4430-9184-6f6a6ca58e3e'
  containerRegistry: 'tringo.azurecr.io'
  imageRepository0: 'frontend'
  dockerfilePath0: '$(Build.SourcesDirectory)/frontend/Dockerfile'
  imageRepository1: 'order-service'
  dockerfilePath1: '$(Build.SourcesDirectory)/order-service/Dockerfile'
  imageRepository2: 'product-service'
  dockerfilePath2: '$(Build.SourcesDirectory)/product-service/Dockerfile'
  imageRepository3: 'user-service'
  dockerfilePath3: '$(Build.SourcesDirectory)/user-service/Dockerfile'
  tag: '$(Build.BuildId)'

  imagePullSecret: 'tringoarc-auth'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push
  variables:
    dburl: $(dbCredUrl)
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)'
        targetFiles: '**/config.py'
        encoding: 'auto'
        tokenPattern: 'custom'
        tokenPrefix: '#'
        tokenSuffix: '#'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
    - task: Docker@2
      inputs:
        containerRegistry: '$(containerRegistry)'
        command: 'login'
    - script: "docker pull $(containerRegistry)/$(imageRepository0):latest"
      displayName: Pull latest $(imageRepository0) for layer caching
      continueOnError: true     
    - script: "docker pull $(containerRegistry)/$(imageRepository1):latest"
      displayName: Pull latest $(imageRepository1) for layer caching
      continueOnError: true 
    - script: "docker pull $(containerRegistry)/$(imageRepository2):latest"
      displayName: Pull latest $(imageRepository2) for layer caching
      continueOnError: true 
    - script: "docker pull $(containerRegistry)/$(imageRepository3):latest"
      displayName: Pull latest $(imageRepository3) for layer caching
      continueOnError: true 

    - task: Docker@2
      displayName: Build an image $(imageRepository0)
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository0)'
        Dockerfile: '$(dockerfilePath0)'
        command: 'build'
        arguments: '--cache-from=$(containerRegistry)/$(imageRepository0):latest'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push an image $(imageRepository0) to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        command: 'push'
        repository: '$(imageRepository0)'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build an image $(imageRepository1)
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository1)'
        Dockerfile: '$(dockerfilePath1)'
        command: 'build'
        arguments: '--cache-from=$(containerRegistry)/$(imageRepository1):latest'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push an image $(imageRepository1) to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        command: 'push'
        repository: '$(imageRepository1)'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build an image $(imageRepository2)
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository2)'
        Dockerfile: '$(dockerfilePath2)'
        command: 'build'
        arguments: '--cache-from=$(containerRegistry)/$(imageRepository2):latest'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push an image $(imageRepository2) to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        command: 'push'
        repository: '$(imageRepository2)'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build an image $(imageRepository3)
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository3)'
        Dockerfile: '$(dockerfilePath3)'
        command: 'build'
        arguments: '--cache-from=$(containerRegistry)/$(imageRepository3):latest'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Push an image $(imageRepository3) to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        command: 'push'
        repository: '$(imageRepository3)'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/deploy/aks'
        artifact: 'manifests'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  variables:
    replica-no: 1
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'trisngoflaskmicroservicesdeployment.default'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Manifests
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(imagePullSecret)'
              dockerRegistryEndpoint: '$(dockerRegistryServiceConnection)'
          - task: replacetokens@5
            displayName: Replace Token
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/manifests'
              targetFiles: '**/*.yaml'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/frontend-deployment.yaml
                $(Pipeline.Workspace)/manifests/ingress-service.yaml
                $(Pipeline.Workspace)/manifests/mysql-deployment.yaml
                $(Pipeline.Workspace)/manifests/mysql-secret.yaml
                $(Pipeline.Workspace)/manifests/order-deployment.yaml
                $(Pipeline.Workspace)/manifests/product-deployment.yaml
                $(Pipeline.Workspace)/manifests/user-deployment.yaml
              containers: |
                $(containerRegistry)/$(imageRepository0):$(tag)
                $(containerRegistry)/$(imageRepository1):$(tag)
                $(containerRegistry)/$(imageRepository2):$(tag)
                $(containerRegistry)/$(imageRepository3):$(tag)
              imagePullSecrets: '$(imagePullSecret)'