name: Build and deploy containers to Azure Kubernetes Service
env:
  REGISTRY_NAME: tringo
  CLUSTER_NAME: ProjectAKSCluster
  CLUSTER_RESOURCE_GROUP: ProjectRSGroup
  NAMESPACE: default
  APP_NAME_0: frontend
  APP_NAME_1: order-service
  APP_NAME_2: product-service
  APP_NAME_3: user-service
  SECRET: tringoarc-auth

  
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: "Connect to ACR"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: "Build & push ${{ env.APP_NAME_0 }} container"
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_0 }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_0 }}
      working-directory: ./${{ env.APP_NAME_0 }}
      
    - name: "Build & push ${{ env.APP_NAME_1 }} container"
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_1 }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_1 }}
      working-directory: ./${{ env.APP_NAME_1 }}
      
    - name: "Build & push ${{ env.APP_NAME_2 }} container"
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_2 }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_2 }}
      working-directory: ./${{ env.APP_NAME_2 }}
      
    - name: "Build & push ${{ env.APP_NAME_3 }} container"
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_3 }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_3 }}
      working-directory: ./${{ env.APP_NAME_3 }}
   
    - name: "Upload manifest"
      uses: actions/upload-artifact@v3
      with:
        name: manifests
        path: ./deploy/k8s

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: "Download manifests"
        uses: actions/download-artifact@v3
        with:
          name: manifests

      - name: "Connect AKS"
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Set target AKS cluster"
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          
      - name: Create namespace if doesn't exist
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -
          
      - name: "Create image pull secret for ACR"
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}
          arguments: --force true
        

      - name: "Deploy to AKS"
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            ${{ github.workspace }}/frontend-deployment.yaml
            ${{ github.workspace }}/ingress-service.yaml
            ${{ github.workspace }}/mysql-deployment.yaml
            ${{ github.workspace }}/mysql-secret.yaml
            ${{ github.workspace }}/order-deployment.yaml
            ${{ github.workspace }}/product-deployment.yaml
            ${{ github.workspace }}/user-deployment.yaml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_0 }}
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_1 }}
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_2 }}
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME_3 }}
          imagepullsecrets: |
            ${{ env.SECRET }}
          namespace: ${{ env.NAMESPACE }}